<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>source.nitrogen</string>
        <key>name</key>
        <string>Nitrogen</string>
        <key>comment</key>
        <string>Nitrogen language</string>
        <key>fileTypes</key>
        <array>
            <string>ni</string>
        </array>
        <key>foldingStartMarker</key>
        <string>({|\()\s*$</string>
        <key>foldingStopMarker</key>
        <string>(}|\))\s*$</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>comment</key>
                <string>Block comment</string>
                <key>begin</key>
                <string>/\*</string>
                <key>end</key>
                <string>\*/</string>
                <key>captures</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.comment.nitrogen</string>
                    </dict>
                </array>
                <key>name</key>
                <string>comment.block.nitrogen</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>Single line, double-slash comment</string>
                <key>begin</key>
                <string>//</string>
                <key>beginCaptures</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.comment.nitrogen</string>
                    </dict>
                </array>
                <key>end</key>
                <string>$</string>
                <key>name</key>
                <string>comment.line.double-slash.nitrogen</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>Single line, number-sign comment</string>
                <key>begin</key>
                <string>#</string>
                <key>beginCaptures</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.comment.nitrogen</string>
                    </dict>
                </array>
                <key>end</key>
                <string>$</string>
                <key>name</key>
                <string>comment.line.number-sign.nitrogen</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>Number literal</string>
                <key>match</key>
                <string>\b([0-9]+\.?[0-9]*)\b</string>
                <key>name</key>
                <string>constant.numeric.nitrogen</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>Double quoted string literal</string>
                <key>begin</key>
                <string>"</string>
                <key>beginCaptures</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.begin.nitrogen</string>
                    </dict>
                </array>
                <key>end</key>
                <string>"</string>
                <key>endCaptures</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>punctuation.definition.string.end.nitrogen</string>
                    </dict>
                </array>
                <key>name</key>
                <string>string.quoted.double.nitrogen</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>Functions</string>
                <key>match</key>
                <string>(\bfunc\b)|([a-zA-Z_]\w*)(?=\()</string>
                <key>captures</key>
                <dict>
                    <key>1</key>
                    <dict>
                        <key>name</key>
                        <string>keyword.function.go</string>
                    </dict>
                    <key>2</key>
                    <dict>
                        <key>name</key>
                        <string>support.function.go</string>
                    </dict>
                </dict>
            </dict>
            <dict>
                <key>comment</key>
                <string>Language constants</string>
                <key>match</key>
                <string>\b(true|false|nil)\b</string>
                <key>name</key>
                <string>constant.language.nitrogen</string>
            </dict>
            <dict>
                <key>comment</key>
                <string>Variable definition</string>
                <key>match</key>
                <string>(def)\s([a-zA-Z_]+)\b</string>
                <key>captures</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.var.nitrogen</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>variable.other.assignment.nitrogen</string>
                    </dict>
                </array>
            </dict>
            <dict>
                <key>comment</key>
                <string>Terminators</string>
                <key>match</key>
                <string>;</string>
                <key>name</key>
                <string>punctuation.terminator.nitrogen</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#brackets</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#delimiters</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#keywords</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#operators</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>brackets</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>\{|\}</string>
                        <key>name</key>
                        <string>punctuation.other.bracket.curly.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\(|\)</string>
                        <key>name</key>
                        <string>punctuation.other.bracket.round.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\[|\]</string>
                        <key>name</key>
                        <string>punctuation.other.bracket.square.nitrogen</string>
                    </dict>
                </array>
            </dict>
            <key>delimiters</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>,</string>
                        <key>name</key>
                        <string>punctuation.other.comma.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\.(?!\.\.)</string>
                        <key>name</key>
                        <string>punctuation.other.period.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>:(?!=)</string>
                        <key>name</key>
                        <string>punctuation.other.colon.nitrogen</string>
                    </dict>
                </array>
            </dict>
            <key>keywords</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>comment</key>
                        <string>Flow control keywords</string>
                        <key>match</key>
                        <string>\b(else|if|return)\b</string>
                        <key>name</key>
                        <string>keyword.control.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\bconst\b</string>
                        <key>name</key>
                        <string>keyword.const.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\bfunc\b</string>
                        <key>name</key>
                        <string>keyword.function.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\bdef\b</string>
                        <key>name</key>
                        <string>keyword.var.nitrogen</string>
                    </dict>
                </array>
            </dict>
            <key>operators</key>
            <dict>
                <key>comment</key>
                <string>Note that the order here is very important!</string>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>match</key>
                        <string>\-\-</string>
                        <key>name</key>
                        <string>keyword.operator.decrement.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>\+\+</string>
                        <key>name</key>
                        <string>keyword.operator.increment.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(==|!=|&amp;lt;=|&amp;gt;=|&amp;lt;[^&amp;lt;]|&amp;gt;[^&amp;gt;])</string>
                        <key>name</key>
                        <string>keyword.operator.comparison.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(&amp;&amp;|\|\||!)</string>
                        <key>name</key>
                        <string>keyword.operator.logical.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(=|\+=|\-=|\|=|\^=|\*=|/=|:=|%=|&amp;lt;&amp;lt;=|&amp;gt;&amp;gt;=|&amp;\^=|&amp;=)</string>
                        <key>name</key>
                        <string>keyword.operator.assignment.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(\+|\-|\*|/|%)</string>
                        <key>name</key>
                        <string>keyword.operator.arithmetic.nitrogen</string>
                    </dict>
                    <dict>
                        <key>match</key>
                        <string>(&amp;(?!\^)|\||\^|&amp;\^|&amp;lt;&amp;lt;|&amp;gt;&amp;gt;)</string>
                        <key>name</key>
                        <string>keyword.operator.arithmetic.bitwise.nitrogen</string>
                    </dict>
                </array>
            </dict>
        </dict>
    </dict>
</plist>